# Generate Data for Object Storage

In [1]:
import pandas as pd
import numpy as np
from deltalake.writer import write_deltalake

In [2]:
data_dict = {
    'date': [(pd.Timestamp.now() - pd.Timedelta(days=i)).date() for i in range(99, -1, -1)],
    'name': [''.join(np.random.choice(list('abcdefghijklmnopqrstuvwxyz'), size=8)) for _ in range(100)],
    'price': np.random.random(100).tolist(),
    'quantity': np.random.randint(1, 1000, size=100).tolist(),
}

df = pd.DataFrame(data_dict)
df.head()

         date      name     price  quantity
0  2026-01-25  khbfxmum  0.483862       636
1  2026-01-26  squsgagm  0.639600       701
2  2026-01-27  wwifqefi  0.799017       415
3  2026-01-28  szzhjbid  0.864840       193
4  2026-01-29  xoyioyfx  0.348505        68

In [3]:
split_idx = np.array_split(df.index, 3)
df_part_1, df_part_2, df_part_3 = [df.loc[idx].reset_index(drop=True) for idx in split_idx]
df_part_1, df_part_2, df_part_3

(          date      name     price  quantity
 0   2026-01-25  khbfxmum  0.483862       636
 1   2026-01-26  squsgagm  0.639600       701
 2   2026-01-27  wwifqefi  0.799017       415
 3   2026-01-28  szzhjbid  0.864840       193
 4   2026-01-29  xoyioyfx  0.348505        68
 5   2026-01-30  wbhpzhrv  0.412857       599
 6   2026-01-31  oqohotqv  0.646389       109
 7   2026-02-01  vppxtwrc  0.698620       236
 8   2026-02-02  xyyzpxkb  0.796432       183
 9   2026-02-03  mzdfrjef  0.361527       707
 10  2026-02-04  ewctcnog  0.208249       554
 11  2026-02-05  hnovwhkv  0.492218       704
 12  2026-02-06  svvyslzs  0.200349       205
 13  2026-02-07  uvlbylmj  0.025898       197
 14  2026-02-08  wwgvauvf  0.223666        66
 15  2026-02-09  hddjkcet  0.531274       621
 16  2026-02-10  teeljsfn  0.791059       769
 17  2026-02-11  fbzjxuch  0.505273       313
 18  2026-02-12  bubxkuzy  0.360554       345
 19  2026-02-13  bpsljizq  0.421092       684
 20  2026-02-14  obcbyqwz  0.965211       621
 21  2026-02-15  yvhsdqpn  0.075624        86
 22  2026-02-16  kdnftnec  0.734037       188
 23  2026-02-17  fbnpdakz  0.610940       825
 24  2026-02-18  tstjzaba  0.524283       520
 25  2026-02-19  uezvnjgp  0.993280       277
 26  2026-02-20  bzsfhfdm  0.198705       359
 27  2026-02-21  wdzqirtb  0.602306       901
 28  2026-02-22  uxquhyrj  0.089196       929
 29  2026-02-23  pzfxtkcc  0.299159       278
 30  2026-02-24  tcpbuydb  0.424779       498
 31  2026-02-25  rkugrkpo  0.719951       556
 32  2026-02-26  nxsnkcsd  0.065174       529
 33  2026-02-27  nhikaxcp  0.547771       369,
           date      name     price  quantity
 0   2026-02-28  jysjijdb  0.000941       171
 1   2026-03-01  cwtptctv  0.818903       631
 2   2026-03-02  fhyoormu  0.460111       927
 3   2026-03-03  rkxwutxs  0.815980       514
 4   2026-03-04  ihwuoias  0.463647       742
 5   2026-03-05  qduzbwfr  0.319373       100
 6   2026-03-06  ittjqhfv  0.297128       158
 7   2026-03-07  hgnbgomi  0.542608       670
 8   2026-03-08  nhjdyfam  0.713074       567
 9   2026-03-09  nglvcdzg  0.092684       264
 10  2026-03-10  iaxmsfmk  0.269597       911
 11  2026-03-11  nfgdeqvf  0.351433       610
 12  2026-03-12  cmdqjzje  0.987021       823
 13  2026-03-13  ejogneev  0.424279       199
 14  2026-03-14  rimwhhxj  0.716685       244
 15  2026-03-15  flmwofid  0.000591       448
 16  2026-03-16  eufhhdcc  0.406141       147
 17  2026-03-17  sqntcfht  0.504041       931
 18  2026-03-18  pwhkynwy  0.526422       723
 19  2026-03-19  dacajatq  0.309940       689
 20  2026-03-20  mbzjtbqh  0.904113       605
 21  2026-03-21  tekwlwqt  0.670317       414
 22  2026-03-22  uqnqgyoa  0.571994       169
 23  2026-03-23  pmsuigdn  0.058382       453
 24  2026-03-24  llzcecii  0.817837       269
 25  2026-03-25  xoxfjhqd  0.653915       885
 26  2026-03-26  rqzluksl  0.520019       285
 27  2026-03-27  fpsmbdcg  0.313523       451
 28  2026-03-28  ydmgjfmo  0.916570       328
 29  2026-03-29  ucjchxkt  0.925216       421
 30  2026-03-30  maskqmjg  0.601717       695
 31  2026-03-31  cywojlnx  0.969265       846
 32  2026-04-01  qdtszlwm  0.365158       889,
           date      name     price  quantity
 0   2026-04-02  twfyjhyx  0.559161       232
 1   2026-04-03  jbhxnmxe  0.337238       989
 2   2026-04-04  gxxbdmru  0.475648       593
 3   2026-04-05  kzwbriib  0.242623       911
 4   2026-04-06  sxeladew  0.184896       429
 5   2026-04-07  ucmxxbqb  0.899451       289
 6   2026-04-08  uetoaxax  0.024632       581
 7   2026-04-09  wwqwtxvz  0.919056       975
 8   2026-04-10  pvqsdsey  0.469879       863
 9   2026-04-11  zkpkkstj  0.348047       100
 10  2026-04-12  gynqqeko  0.675765       687
 11  2026-04-13  qyuednjk  0.948271       913
 12  2026-04-14  wtmklbwq  0.627706       107
 13  2026-04-15  hxafwvie  0.685112        46
 14  2026-04-16  alfazpdg  0.243407       909
 15  2026-04-17  vmkeeygo  0.337022        37
 16  2026-04-18  fqczdxst  0.053589       381
 17  2026-04-19  hytezubr  0.250142       728
 18  2026-04-20  xebfnnsh  0.210829       816
 19  2026-04-21  kadagbkd  0.122749       379
 20  2026-04-22  ibfubnxg  0.034432       675
 21  2026-04-23  pfmteczf  0.932942       243
 22  2026-04-24  ucdntkcw  0.017290        45
 23  2026-04-25  twtbpsqt  0.095324       903
 24  2026-04-26  lysbaltq  0.113594       873
 25  2026-04-27  dyazsczw  0.278157       313
 26  2026-04-28  awoayydg  0.161563       768
 27  2026-04-29  skbhamno  0.423093        91
 28  2026-04-30  cuqusvmj  0.469513       839
 29  2026-05-01  kcopdjip  0.792618       474
 30  2026-05-02  btyvdxym  0.712286       886
 31  2026-05-03  ovofugif  0.920838       941
 32  2026-05-04  sabvajma  0.773621       302)

In [4]:
all_df:list[pd.DataFrame] = [df_part_1, df_part_2, df_part_3]
for idx, part in enumerate(all_df):
    write_deltalake(f'../../../data/test/lh/part_{idx}', part)

In [5]:
tmp_df = pd.read_parquet('../../../data/test/lh/part_0/part-00000-6583b2a0-1a7f-474a-986d-1265b0833ba2-c000.snappy.parquet')
tmp_df.head()

         date      name     price  quantity
0  2026-01-25  khbfxmum  0.483862       636
1  2026-01-26  squsgagm  0.639600       701
2  2026-01-27  wwifqefi  0.799017       415
3  2026-01-28  szzhjbid  0.864840       193
4  2026-01-29  xoyioyfx  0.348505        68