# Generate Data for Object Storage

In [1]:
import pandas as pd
import numpy as np

In [2]:
data_dict = {
    'name': [''.join(np.random.choice(list('abcdefghijklmnopqrstuvwxyz'), size=8)) for _ in range(100)],
    'price': np.random.random(100).tolist(),
    'quantity': np.random.randint(1, 10_000, size=100).tolist(),
}

data_dict

{'name': ['uhbbgmmt',
  'rscmenmz',
  'judjobvn',
  'xiyayhei',
  'ogtgukcy',
  'awnhjpsb',
  'wdtftgwn',
  'sfrbykjv',
  'raowrpks',
  'wbgcpgqs',
  'mhglwbns',
  'luolblhz',
  'spzgbqrc',
  'ojtxeffw',
  'mgghjnnm',
  'pbikhkcg',
  'hjddobel',
  'mbqufngl',
  'cmntavgq',
  'ihsanbvk',
  'cbegbegg',
  'eanorxxt',
  'jjhsvemk',
  'lxjzfbhc',
  'rsqnljxb',
  'dbiadktx',
  'svolvdkd',
  'erdcpzyy',
  'kmzfdjxk',
  'isaytvwy',
  'dorjkihv',
  'wxiticxu',
  'dydwrkxt',
  'watsvqgy',
  'whuqlecl',
  'kbbluuss',
  'bupwkjtc',
  'twyvbqli',
  'gjmmktxy',
  'laxrsnvi',
  'hvfopwlz',
  'xljusmhx',
  'oaiwclcf',
  'dmbhyrzj',
  'idibbnfi',
  'wdxnsmln',
  'xruzsufx',
  'emwssqfw',
  'ipdszbly',
  'magrgiwy',
  'nrkzzwvc',
  'iogbcqiz',
  'hkiwkkuh',
  'diqegunb',
  'nhvwnpru',
  'cvadvwkq',
  'tsgtcnzf',
  'mqebqiwj',
  'zwkmvwqn',
  'atiaufit',
  'pznygqmy',
  'jizyjmkj',
  'zxigzehi',
  'ohxnokuq',
  'coxubgqd',
  'bqhbrhlt',
  'ipideyay',
  'txkxhdgm',
  'wxksalvp',
  'mxuvabav',
  'lcbpcjbf',
  'bomiyvyv',
  'vyfhzfba',
  'ettipusp',
  'fkasuslr',
  'zvsectmk',
  'segebkpz',
  'dclyuqyb',
  'agwaqvjg',
  'xermddez',
  'djmcczic',
  'cxffgizr',
  'qhrawkaq',
  'qqwoyydo',
  'yshqojvi',
  'qqsfpurt',
  'rjqzenzk',
  'azuzglfb',
  'kpdlurex',
  'wavqvzfi',
  'vxyzbnwh',
  'imhduwin',
  'dotupdfb',
  'wpoysptv',
  'ezhfsgqt',
  'seehimou',
  'wmjhxspj',
  'culfnvse',
  'yzddpzgr',
  'ckgtzcpo'],
 'price': [0.7105815889496139,
  0.15443547741790697,
  0.9629125208836482,
  0.025263275129482232,
  0.7901017206174085,
  0.4934751289778674,
  0.6335065169516078,
  0.7073019313766127,
  0.5648590288074817,
  0.4974714132774435,
  0.18048746060218857,
  0.5168769857413725,
  0.736181558173155,
  0.357200018090989,
  0.6060332981730656,
  0.11832430565806151,
  0.06331903573125053,
  0.24525258688061902,
  0.8783908045890672,
  0.6521065334761655,
  0.1541155974083046,
  0.5261938802817079,
  0.6634645758062379,
  0.3212926824265079,
  0.022548597111909374,
  0.5427810210631319,
  0.7592451568295839,
  0.9321736967584996,
  0.9429513285952131,
  0.9663214785060475,
  0.7126045958165845,
  0.9903961683985031,
  0.527569161770435,
  0.36698084171012924,
  0.8919831195564937,
  0.9892609268362255,
  0.8476015593635217,
  0.9314183400784429,
  0.2437683002026535,
  0.006088688005574716,
  0.004706434757398625,
  0.32317403117270527,
  0.07975646136402481,
  0.07732772188351555,
  0.22407397301624377,
  0.014214026200273011,
  0.6752559815839246,
  0.35694894914901754,
  0.26031108932444025,
  0.23853461071782145,
  0.7858000585026438,
  0.05009361813850366,
  0.5619176862085411,
  0.7005783274620294,
  0.05736898034322557,
  0.5804983129638421,
  0.6681344466750141,
  0.9145932006597665,
  0.4520268476078865,
  0.23062590271436856,
  0.7453166448717785,
  0.014545858864334349,
  0.2593193657818963,
  0.9978323127632974,
  0.9971334333507891,
  0.45850363155367746,
  0.24429513510972667,
  0.39779684639889545,
  0.5748350439074676,
  0.1007655519594094,
  0.2305863192655766,
  0.1396825912160342,
  0.24775006511765219,
  0.6399826868285317,
  0.8790721236595695,
  0.8728589716169007,
  0.20488678889254153,
  0.9972678058179967,
  0.24441766959663924,
  0.23953743028836194,
  0.8174526254201003,
  0.313021074181679,
  0.33113685796861936,
  0.7145992509797856,
  0.25579032021290293,
  0.1549410484072078,
  0.26875964548294184,
  0.803534170256095,
  0.5926946484972269,
  0.43645218786981566,
  0.23901064305442044,
  0.5715889373898455,
  0.6118112440343219,
  0.9943030434353471,
  0.9658460859670055,
  0.3962055265321037,
  0.002541792983739466,
  0.6148653165850431,
  0.35519177770134347,
  0.24861942767786427],
 'quantity': [3476,
  3013,
  929,
  8686,
  8607,
  1550,
  6138,
  6861,
  8291,
  1064,
  464,
  1335,
  4089,
  710,
  7848,
  9226,
  5586,
  8988,
  7344,
  1325,
  5161,
  6138,
  476,
  3077,
  6889,
  6956,
  8032,
  5352,
  7094,
  5920,
  5589,
  9058,
  4172,
  8748,
  3633,
  3291,
  2134,
  3918,
  9730,
  7604,
  3530,
  1605,
  9663,
  8143,
  3193,
  4014,
  90,
  1921,
  4255,
  1539,
  7540,
  4229,
  6975,
  328,
  1857,
  7772,
  376,
  2730,
  5954,
  5958,
  1883,
  3339,
  4715,
  3791,
  1829,
  3251,
  3392,
  2483,
  1311,
  6023,
  289,
  6826,
  7586,
  5047,
  3365,
  1485,
  6260,
  6482,
  4703,
  8080,
  6438,
  5791,
  7470,
  5332,
  7773,
  8923,
  6893,
  686,
  4989,
  8925,
  1004,
  2640,
  2269,
  6891,
  2274,
  6509,
  6788,
  3644,
  6518,
  1343]}

In [3]:
df = pd.DataFrame(data_dict)
df

        name     price  quantity
0   uhbbgmmt  0.710582      3476
1   rscmenmz  0.154435      3013
2   judjobvn  0.962913       929
3   xiyayhei  0.025263      8686
4   ogtgukcy  0.790102      8607
..       ...       ...       ...
95  seehimou  0.396206      6509
96  wmjhxspj  0.002542      6788
97  culfnvse  0.614865      3644
98  yzddpzgr  0.355192      6518
99  ckgtzcpo  0.248619      1343

[100 rows x 3 columns]

In [4]:
# df_part_1, df_part_2, df_part_3 = np.array_split(df, 3)
# df_part_1, df_part_2, df_part_3

split_idx = np.array_split(df.index, 3)
df_part_1, df_part_2, df_part_3 = [df.loc[idx].reset_index(drop=True) for idx in split_idx]
df_part_1, df_part_2, df_part_3

(        name     price  quantity
 0   uhbbgmmt  0.710582      3476
 1   rscmenmz  0.154435      3013
 2   judjobvn  0.962913       929
 3   xiyayhei  0.025263      8686
 4   ogtgukcy  0.790102      8607
 5   awnhjpsb  0.493475      1550
 6   wdtftgwn  0.633507      6138
 7   sfrbykjv  0.707302      6861
 8   raowrpks  0.564859      8291
 9   wbgcpgqs  0.497471      1064
 10  mhglwbns  0.180487       464
 11  luolblhz  0.516877      1335
 12  spzgbqrc  0.736182      4089
 13  ojtxeffw  0.357200       710
 14  mgghjnnm  0.606033      7848
 15  pbikhkcg  0.118324      9226
 16  hjddobel  0.063319      5586
 17  mbqufngl  0.245253      8988
 18  cmntavgq  0.878391      7344
 19  ihsanbvk  0.652107      1325
 20  cbegbegg  0.154116      5161
 21  eanorxxt  0.526194      6138
 22  jjhsvemk  0.663465       476
 23  lxjzfbhc  0.321293      3077
 24  rsqnljxb  0.022549      6889
 25  dbiadktx  0.542781      6956
 26  svolvdkd  0.759245      8032
 27  erdcpzyy  0.932174      5352
 28  kmzfdjxk  0.942951      7094
 29  isaytvwy  0.966321      5920
 30  dorjkihv  0.712605      5589
 31  wxiticxu  0.990396      9058
 32  dydwrkxt  0.527569      4172
 33  watsvqgy  0.366981      8748,
         name     price  quantity
 0   whuqlecl  0.891983      3633
 1   kbbluuss  0.989261      3291
 2   bupwkjtc  0.847602      2134
 3   twyvbqli  0.931418      3918
 4   gjmmktxy  0.243768      9730
 5   laxrsnvi  0.006089      7604
 6   hvfopwlz  0.004706      3530
 7   xljusmhx  0.323174      1605
 8   oaiwclcf  0.079756      9663
 9   dmbhyrzj  0.077328      8143
 10  idibbnfi  0.224074      3193
 11  wdxnsmln  0.014214      4014
 12  xruzsufx  0.675256        90
 13  emwssqfw  0.356949      1921
 14  ipdszbly  0.260311      4255
 15  magrgiwy  0.238535      1539
 16  nrkzzwvc  0.785800      7540
 17  iogbcqiz  0.050094      4229
 18  hkiwkkuh  0.561918      6975
 19  diqegunb  0.700578       328
 20  nhvwnpru  0.057369      1857
 21  cvadvwkq  0.580498      7772
 22  tsgtcnzf  0.668134       376
 23  mqebqiwj  0.914593      2730
 24  zwkmvwqn  0.452027      5954
 25  atiaufit  0.230626      5958
 26  pznygqmy  0.745317      1883
 27  jizyjmkj  0.014546      3339
 28  zxigzehi  0.259319      4715
 29  ohxnokuq  0.997832      3791
 30  coxubgqd  0.997133      1829
 31  bqhbrhlt  0.458504      3251
 32  ipideyay  0.244295      3392,
         name     price  quantity
 0   txkxhdgm  0.397797      2483
 1   wxksalvp  0.574835      1311
 2   mxuvabav  0.100766      6023
 3   lcbpcjbf  0.230586       289
 4   bomiyvyv  0.139683      6826
 5   vyfhzfba  0.247750      7586
 6   ettipusp  0.639983      5047
 7   fkasuslr  0.879072      3365
 8   zvsectmk  0.872859      1485
 9   segebkpz  0.204887      6260
 10  dclyuqyb  0.997268      6482
 11  agwaqvjg  0.244418      4703
 12  xermddez  0.239537      8080
 13  djmcczic  0.817453      6438
 14  cxffgizr  0.313021      5791
 15  qhrawkaq  0.331137      7470
 16  qqwoyydo  0.714599      5332
 17  yshqojvi  0.255790      7773
 18  qqsfpurt  0.154941      8923
 19  rjqzenzk  0.268760      6893
 20  azuzglfb  0.803534       686
 21  kpdlurex  0.592695      4989
 22  wavqvzfi  0.436452      8925
 23  vxyzbnwh  0.239011      1004
 24  imhduwin  0.571589      2640
 25  dotupdfb  0.611811      2269
 26  wpoysptv  0.994303      6891
 27  ezhfsgqt  0.965846      2274
 28  seehimou  0.396206      6509
 29  wmjhxspj  0.002542      6788
 30  culfnvse  0.614865      3644
 31  yzddpzgr  0.355192      6518
 32  ckgtzcpo  0.248619      1343)

In [5]:
all_df:list[pd.DataFrame] = [df_part_1, df_part_2, df_part_3]
for idx, part in enumerate(all_df):
    part.to_parquet(f'../../../data/test/dl/part_{idx}.parquet')

In [6]:
tmp_df = pd.read_parquet('../../../data/test/dl/part_1.parquet')
tmp_df.head()

       name     price  quantity
0  whuqlecl  0.891983      3633
1  kbbluuss  0.989261      3291
2  bupwkjtc  0.847602      2134
3  twyvbqli  0.931418      3918
4  gjmmktxy  0.243768      9730